name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Client (React) Job
  client:
    name: Client - React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Client Dependencies
        working-directory: client
        run: npm install

      - name: Lint Client Code
        working-directory: client
        run: npm run lint

      - name: Test Client Code
        working-directory: client
        run: npm test -- --watchAll=false

      - name: Build Client App
        working-directory: client
        run: npm run build

  # Server (Node.js) Job
  server:
    name: Server - Node.js Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Server Dependencies
        working-directory: server
        run: npm install

      - name: Lint Server Code
        working-directory: server
        run: npm run lint

      - name: Test Server Code
        working-directory: server
        run: npm test
